apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cockroach-system-operator

resources:
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/install/crds.yaml
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/install/operator.yaml
